version: '3.8'

services:
  # Backend API
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - MONGO_URI=mongodb://mongodb:27017/shira_analytics
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - mongodb
      - redis
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - shira-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shira_streaming
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shira-network

  # MongoDB
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - shira-network

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - shira-network

volumes:
  postgres-data:
  mongodb-data:
  redis-data:

networks:
  shira-network:
    driver: bridge
